#!/usr/bin/env bash
# deploy/install_backend.sh
# =========================
# One-shot installer for the Destiny Voyager FastAPI backend on the
# Hostinger VPS (root@187.77.200.241).
#
# Idempotent: re-running updates the checkout, re-installs deps, and
# reloads systemd. Safe to run after every push.
#
# Run on the VPS as root:
#   bash install_backend.sh
#
# Or remotely from a workstation:
#   scp install_backend.sh root@VPS:/tmp/
#   ssh root@VPS bash /tmp/install_backend.sh

set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/destiny-voyager}"
REPO_URL="${REPO_URL:-https://github.com/clarencestephen/destiny-voyager.git}"
BRANCH="${BRANCH:-main}"
SERVICE_NAME="destiny-voyager-backend"
SERVICE_USER="${SERVICE_USER:-www-data}"
ENV_FILE="${INSTALL_DIR}/backend/.env"

echo "▲ Destiny Voyager backend installer"
echo "  install dir: ${INSTALL_DIR}"
echo "  branch:      ${BRANCH}"
echo

# ── 1. System dependencies ─────────────────────────────────────
echo "[1/6] apt packages"
apt-get update -qq
apt-get install -y -qq python3-venv python3-pip git nginx >/dev/null

# ── 2. Clone or update repo ─────────────────────────────────────
echo "[2/6] repo"
if [[ -d "${INSTALL_DIR}/.git" ]]; then
    git -C "${INSTALL_DIR}" fetch --quiet origin "${BRANCH}"
    git -C "${INSTALL_DIR}" reset --hard "origin/${BRANCH}"
    echo "  ✓ updated to $(git -C ${INSTALL_DIR} rev-parse --short HEAD)"
else
    git clone --quiet --branch "${BRANCH}" --depth 50 "${REPO_URL}" "${INSTALL_DIR}"
    echo "  ✓ cloned to ${INSTALL_DIR}"
fi

# ── 3. Virtualenv + Python deps ────────────────────────────────
echo "[3/6] venv + pip"
if [[ ! -d "${INSTALL_DIR}/.venv" ]]; then
    python3 -m venv "${INSTALL_DIR}/.venv"
fi
"${INSTALL_DIR}/.venv/bin/pip" install -q --upgrade pip
"${INSTALL_DIR}/.venv/bin/pip" install -q -r "${INSTALL_DIR}/backend/requirements.txt"
echo "  ✓ deps installed"

# ── 4. .env (only create if missing — never overwrite) ─────────
echo "[4/6] .env"
if [[ ! -f "${ENV_FILE}" ]]; then
    cat > "${ENV_FILE}" <<EOF
# Generated by install_backend.sh — fill in real values then restart service.
BACKEND_CORS_ORIGINS=https://destiny-voyager.clarencestephen.com,http://localhost:5173
PUBLIC_BASE_URL=https://destiny-voyager.clarencestephen.com
BACKEND_ENV=production
EOF
    echo "  + created ${ENV_FILE} — edit it, then restart the service"
else
    echo "  ✓ ${ENV_FILE} already present (not touching)"
fi
# .env must be readable by the service user; 640 + correct owner.
chown "${SERVICE_USER}:${SERVICE_USER}" "${ENV_FILE}"
chmod 640 "${ENV_FILE}"
# Service user also needs to read the repo (clone defaults to root-owned) +
# write to data/ for the link store SQLite file.
chown -R "${SERVICE_USER}:${SERVICE_USER}" "${INSTALL_DIR}/.venv" "${INSTALL_DIR}/backend/data"
# Make the repo itself readable + executable (traverse) by the service user.
chmod -R a+rX "${INSTALL_DIR}/backend" "${INSTALL_DIR}/darth-bot"

# ── 5. systemd unit ────────────────────────────────────────────
echo "[5/6] systemd"
cat > "/etc/systemd/system/${SERVICE_NAME}.service" <<EOF
[Unit]
Description=Destiny Voyager FastAPI backend
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_USER}
WorkingDirectory=${INSTALL_DIR}/backend
EnvironmentFile=${ENV_FILE}
ExecStart=${INSTALL_DIR}/.venv/bin/uvicorn main:app --host 127.0.0.1 --port 8090 --proxy-headers
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal

# Hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ReadWritePaths=${INSTALL_DIR}/backend/data
ProtectHome=true

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable "${SERVICE_NAME}" >/dev/null
systemctl restart "${SERVICE_NAME}"
sleep 2
systemctl is-active --quiet "${SERVICE_NAME}" && echo "  ✓ service active" || {
    echo "  ✗ service failed — journalctl -u ${SERVICE_NAME} -n 50"
    journalctl -u "${SERVICE_NAME}" -n 30 --no-pager
    exit 1
}

# ── 6. nginx site config ───────────────────────────────────────
echo "[6/6] nginx"
NGINX_CONF="/etc/nginx/sites-available/destiny-voyager-backend"
cat > "${NGINX_CONF}" <<'EOF'
# Destiny Voyager backend — reverse-proxy → uvicorn @ 127.0.0.1:8090
#
# Listen on port 80 for now. After DNS points
# api.destiny-voyager.clarencestephen.com → this VPS, run:
#   certbot --nginx -d api.destiny-voyager.clarencestephen.com
# to add HTTPS.

server {
    listen 80;
    listen [::]:80;
    server_name api.destiny-voyager.clarencestephen.com _;

    # Cap request body for chat queries
    client_max_body_size 64k;

    location / {
        proxy_pass http://127.0.0.1:8090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
    }

    # Tiny health endpoint, no logs
    location = /health {
        proxy_pass http://127.0.0.1:8090/health;
        access_log off;
    }
}
EOF

ln -sf "${NGINX_CONF}" /etc/nginx/sites-enabled/destiny-voyager-backend
rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
nginx -t >/dev/null 2>&1 && systemctl reload nginx
echo "  ✓ nginx reloaded"

echo
echo "▲ DONE."
echo "  Service:  systemctl status ${SERVICE_NAME}"
echo "  Logs:     journalctl -u ${SERVICE_NAME} -f"
echo "  Test:     curl http://localhost/health"
echo
echo "Next:"
echo "  1. Point api.destiny-voyager.clarencestephen.com → $(hostname -I | awk '{print $1}') (A record in Cloudflare)"
echo "  2. Run: certbot --nginx -d api.destiny-voyager.clarencestephen.com"
echo "  3. Set BACKEND_BASE_URL on the Worker + Discord bot"
